### ISSUE TITLE
search option (-q) didn't work for me without deleting the additional cookies

### ISSUE THREAD

**Issue by atropineal** [minisllc/domainhunter#1]
a nice script, thankyou

for me, the script didn't find results using the -q option.  removing the additional 'annoying' cookies rectified the situation.  i didn't submit a pull request because i'm unsure as to whether the fix would be generally good, or is just 'good for me', for whatever reason

**Comment by andrewchiles** [comment]
Thank you for submitting this issue. This problem seems to be solved with the latest commit. However, this will likely be an ongoing issue as the expireddomains.net site makes changes. Thanks again!
